repos:
  - repo: local
    hooks:
      - id: check-version-consistency
        name: Check version match
        entry: bash scripts/check_version_consistency.sh
        language: system
        always_run: true
        pass_filenames: false